module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
    "./node_modules/flowbite/**/*.js",
  ],
  theme: {
    backgroundImage: {
      "news-1": "url('/src/assets/news-1.jpeg')",
      "news-2": "url('/src/assets/news-2.jpeg')",
      "news-3": "url('/src/assets/news-3.jpeg')",
    },
    extend: {},
    colors: {
      "button-bg": "#6CC551",
      "button-bg-hover": "#83F062",
      "news-section-bg": "#F5F6F6",
      "news-section-text": "#001630",
      "logo-color": "#3a3838",
      "nav-text-color": "#222222",
      "footer-bg": "#1E2833",
      "footer-text": "#E3E4E6",
      gray: "#8492a6",
      "gray-light": "#d3dce6",
      // "50": "#eff6ff",
      // "100": "#dbeafe",
      // "200": "#bfdbfe",
      // "300": "#93c5fd",
      // "400": "#60a5fa",
      // "500": "#3b82f6",
      // "600": "#2563eb",
      // "700": "#1d4ed8",
      // "800": "#1e40af",
      // "900": "#1e3a8a",
    },
  },
  plugins: [require("flowbite/plugin"), require('@tailwindcss/forms')],
};
